
# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  clean:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:9.0.4
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - run: mvn dependency:go-offline
        
      # run clean!
      - run: mvn clean