# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  clean:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11.0-jdk-buster-node-browsers-legacy

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # run clean!
      - run: mvn clean
  deployment:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11.0-jdk-buster-node-browsers-legacy

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
       
      # run deployment!
      - run: mvn deploy -Dmaven.test.skip -DcreateDocs=true -s settings.xml
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11.0-jdk-buster-node-browsers-legacy
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
        
      # run tests!
      # - run: mvn integration-test
      
      # share coverage
      - run: mvn test jacoco:report coveralls:report -DsourceEncoding=UTF-8
      
      # run code analysis using sonarqube
      - run: mvn -Psonar sonar:sonar -DsourceEncoding=UTF-8
      
workflows:
  version: 2
  clean_build_deploy:
    jobs:
      - clean
      - build:
          requires:
            - clean
      - deployment:
          requires:
            - build
